image: gitpod/workspace-full
checkoutLocation: gitpod-k3s
tasks:
  - name: k3s
    command: |
      .gitpod/prepare-k3s.sh
  - name: qemu
    init: |
      .gitpod/install_req_apt.sh
      .gitpod/prepare-rootfs.sh
    command: |
      .gitpod/qemu.sh
